services:
  agro-disaster:
    container_name: agro-disaster
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    networks:
      - db-mysql
      - agro-network
    ports:
      - "8081:8081"
    env_file: .env
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    stdin_open: true
    tty: true
    networks:
      - db-mysql
    volumes:
      - dbdata:/var/lib/mysql
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME

networks:
  db-mysql:
  agro-network:
volumes:
  dbdata: