-- for the password using online bcrypt encoder, encode your password

USE db;

-- ALTER TABLE referral_req
--     ADD CONSTRAINT FK_CREATEDBY
--         FOREIGN KEY (created_by) REFERENCES user(it);
--
-- ALTER TABLE referral_req
--     ADD CONSTRAINT FK_SENDTO
--         FOREIGN KEY (send_to) REFERENCES user(it);
--
-- ALTER TABLE referral_req MODIFY COLUMN id INT auto_increment;
--
-- -- admin inserts(password=admin)
-- INSERT INTO user
--     VALUES ('admin','admin@gmail.com','admin','admin','$2a$12$K/sVWqkl9HCOdU8W5t35sujQuieTapOTtGtAaDm6phMgMwX8WP5ea','ADMIN');
--
-- -- Farmer inserts(password=student)
-- INSERT INTO user
--     VALUES ('it1','christoszal@gmail.com','chris','zalachoris','$2a$12$QhowItiSHmlTHRJmHe0r4OtS78acaxPB9yf9zplBoO4HKTMfotVga','STUDENT');
--
-- INSERT INTO user
--     VALUES ('it2','peterjon@gmail.com','Peter','Jones','$2a$12$QhowItiSHmlTHRJmHe0r4OtS78acaxPB9yf9zplBoO4HKTMfotVga','STUDENT');
--
-- INSERT INTO user
--     VALUES ('it3','jamescasper@gmail.com','James','Casper','$2a$12$QhowItiSHmlTHRJmHe0r4OtS78acaxPB9yf9zplBoO4HKTMfotVga','STUDENT');
--
-- INSERT INTO user
--     VALUES ('it4','bobmor@gmail.com','Bob','Morley','$2a$12$QhowItiSHmlTHRJmHe0r4OtS78acaxPB9yf9zplBoO4HKTMfotVga','STUDENT');
--
-- INSERT INTO user
-- VALUES ('it5','meglaw@gmail.com','Meg','Lawrence','$2a$12$QhowItiSHmlTHRJmHe0r4OtS78acaxPB9yf9zplBoO4HKTMfotVga','STUDENT');
--
-- -- teacher inserts(password=teacher)
-- INSERT INTO user
--     VALUES ('itM1','NickKout@gmail.com','Nick','Koutas','$2a$12$MeyFMSrYO5gnqALy2YfHFeKTX.44ExttX40UoSzwF0YYKN0s.7rnG','TEACHER');
--
-- INSERT INTO user
-- VALUES ('itM2','StivWater@gmail.com','Steven','Water','$2a$12$MeyFMSrYO5gnqALy2YfHFeKTX.44ExttX40UoSzwF0YYKN0s.7rnG','TEACHER');
--
-- INSERT INTO user
-- VALUES ('itM3','bilco@gmail.com','Bill','Cosby','$2a$12$MeyFMSrYO5gnqALy2YfHFeKTX.44ExttX40UoSzwF0YYKN0s.7rnG','TEACHER');
--
-- INSERT INTO user
-- VALUES ('itM4','ShaneWhite@gmail.com','Shane','White','$2a$12$MeyFMSrYO5gnqALy2YfHFeKTX.44ExttX40UoSzwF0YYKN0s.7rnG','TEACHER');
--
-- -- referral requests
--
-- INSERT INTO referral_req
--     VALUES (1,20,'it1','Job','chris','6.5,4.9,8,9','zalachoris','itM1','null');
--
-- INSERT INTO referral_req
--     VALUES (2,20,'it1','Postgraduate','chris','6.5,4.9,8,9','zalachoris','itM3','null');
--
-- INSERT INTO referral_req
--     VALUES (3,21,'it2','Job','Peter','8,7.9,6,10','Jones','itM2','null');
--
-- INSERT INTO referral_req
--     VALUES (4,18,'it3','Job','James','5,4,7,6','Casper','itM1','null');
--
-- INSERT INTO referral_req
--     VALUES (5,21,'it4','Postgraduate','Bob','6,7,8,9','Morley','itM4','null');
--
-- INSERT INTO referral_req
--     VALUES (6,19,'it5','Job','Meg','6,4,7,9','Lawrence','itM1','null');
--
-- INSERT INTO referral_req
--     VALUES (7,22,'it3','Postgraduate','James','8,8,5,6','Casper','itM2','null');
--
-- -- third party inserts
--
-- INSERT INTO third_party
-- VALUES ('Google@gmail.com','Job','Google');
--
-- INSERT INTO third_party
-- VALUES ('Hua@gmail.com','Postgraduate','Hua');
--
-- INSERT INTO third_party
-- VALUES ('Pada@gmail.com','Postgraduate','PADA');
--
-- INSERT INTO third_party
-- VALUES ('Amazon@gmail.com','Job','Amazon');
--
-- INSERT INTO third_party
-- VALUES ('Netflix@gmail.com','Job','Netflix');
--
-- INSERT INTO third_party
-- VALUES ('christoszal@gmail.com','Job','Company');
--
